application: discoverynoob
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: blog.py
  

libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: "2.5.1"